// <auto-generated />
using System;
using MaestroDetalle.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaestroDetalle.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211011031206_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MaestroDetalle.Modelos.ArmarioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ZapatoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmarioId");

                    b.HasIndex("ZapatoId");

                    b.ToTable("ArmarioDetalle");
                });

            modelBuilder.Entity("MaestroDetalle.Modelos.Armarios", b =>
                {
                    b.Property<int>("ArmarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("ArmarioId");

                    b.ToTable("Armarios");
                });

            modelBuilder.Entity("MaestroDetalle.Modelos.Zapatos", b =>
                {
                    b.Property<int>("ZapatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<float>("Size")
                        .HasColumnType("REAL");

                    b.HasKey("ZapatoId");

                    b.ToTable("Zapatos");
                });

            modelBuilder.Entity("MaestroDetalle.Modelos.ArmarioDetalle", b =>
                {
                    b.HasOne("MaestroDetalle.Modelos.Armarios", null)
                        .WithMany("ArmarioDetalle")
                        .HasForeignKey("ArmarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaestroDetalle.Modelos.Zapatos", "Zapato")
                        .WithMany()
                        .HasForeignKey("ZapatoId");

                    b.Navigation("Zapato");
                });

            modelBuilder.Entity("MaestroDetalle.Modelos.Armarios", b =>
                {
                    b.Navigation("ArmarioDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
